# Generated by Django 3.2.12 on 2022-03-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220321_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, default=None, to='api.Tag', verbose_name='Тэг'),
        ),
    ]
