# Generated by Django 3.2.12 on 2022-03-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_color_code_tag_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='units',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='time',
            new_name='cooking_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
