# Generated by Django 3.2.12 on 2022-03-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220330_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', through='api.RecipeIngredients', to='api.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
