version: '3.8'

services:
  # db container
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 2s
      retries: 5


  # backend container
  backend:
    image: inferno2f/foodgram-backend:latest
    depends_on:
      db:
        condition: service_healthy
    restart: always
    # command: >
    #   bash -c "python manage.py migrate &&
    #   python manage.py collectstatic --noinput &&
    #   python manage.py runscript load"
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    env_file:
      - .env
  
  # fronted container
  frontend:
    image: inferno2f/foodgram-front:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend-static/
      - media_value:/var/html/backend-media/
    depends_on:
      - backend


volumes:
  static_value:
  media_value:
  postgres_data: